config/routes.rb
PackB::Application.routes.draw do
  resources :agents

  resources :photos

  scope "(:locale)", :locale => /en|fa/ do  
    resources :pictures
    resources :user_messages

    resources :messages

    resources :categories
    
    resources :products
    resources :licenses

    resources :slides

    resources :users

    resources :pages
  end
  mount Ckeditor::Engine => '/ckeditor'
  
  root :to => 'static#home'
  get "login" => "users#login"  
  get "googlebc5f5c16062b24b0" => "static#googlebc5f5c16062b24b0"  
  get "sitemap.xml" => "static#sitemap", :format => "xml", :as => :sitemap
  post "create_session" => "users#create_session", :as => :create_session
  get "delete_session" => "users#delete_session", :as => :delete_session

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :check_autentication, only: [:show, :edit, :update, :destroy, :index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  def create_session
    user = User.where(:user_name => params[:user_name]).first
    if user.present? and user.password == params[:password]
      session[:admin] = user
      redirect_to :root and return
    else
      session[:admin] = nil
      flash[:partial] = "error"
      render "login"
    end
  end

  def delete_session
    session[:admin] = nil
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :user_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation      
      %ul
        - @user.errors.each do |attr, msg|
          %li= msg

  .field
    = f.label 'نام کاربری:'
    = f.text_field :email
  .field
    = f.label 'رمزعبور:'
    = f.text_field :password
  .actions
    = f.submit 'ثبت', :class => "btn btn-default"

app/views/users/edit.html.haml
.fa.other-page
  %h1 ویرایش اطلاعات مدیرسایت

  = render 'form'

  = link_to 'مشاهده', @user
  \|
  = link_to 'بازگشت', :back

app/views/users/index.html.haml
.fa.other-page  
  %h1 لیست کاربران
  
  %table
    %tr
      %th ایمیل
      %th رمزعبور
      %th
      
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.password
        %td
          = link_to 'مشاهده', user
          = link_to 'ویرایش', edit_user_path(user)
          = link_to 'حذف', user, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }

app/views/users/login.html.haml
.page.fa.other-page  
  %p#notice= notice
  .span3
  .span5
    = form_tag create_session_path do 
      .form-group 
        %span.col-sm-4.lable=" نام کاربری:"
        %span= text_field_tag :user_name, "",:class => "form-control", :placeholder => "نام کاربری را وارد کنید"
      .form-group 
        %span.col-sm-4.lable=" رمز عبور:"
        %span= password_field_tag :password, "", :class => "form-control", :placeholder => "رمز عبور را وارد کنید" 
        
      .form-group.pull-left
        = submit_tag "ورود", :class => "btn btn-default"

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
.page.fa
  .other-page
    %p#notice= notice

    %p
      %b Email:
      = @user.email
    %p
      %b Password:
      = @user.password

    = link_to 'ویرایش', edit_user_path(@user)
    \|
    = link_to 'بازگشت', :back