config/routes.rb
PackB::Application.routes.draw do
  resources :agents

  resources :photos

  scope "(:locale)", :locale => /en|fa/ do  
    resources :pictures
    resources :user_messages

    resources :messages

    resources :categories
    
    resources :products
    resources :licenses

    resources :slides

    resources :users

    resources :pages
  end
  mount Ckeditor::Engine => '/ckeditor'
  
  root :to => 'static#home'
  get "login" => "users#login"  
  get "googlebc5f5c16062b24b0" => "static#googlebc5f5c16062b24b0"  
  get "sitemap.xml" => "static#sitemap", :format => "xml", :as => :sitemap
  post "create_session" => "users#create_session", :as => :create_session
  get "delete_session" => "users#delete_session", :as => :delete_session

end

app/models/agent.rb
# encoding: UTF-8
class Agent < ActiveRecord::Base
  extend FriendlyId  
  friendly_id :name_fa
  def name
    if I18n.locale == :en
      self.read_attribute("name_en")
    else
      self.read_attribute("name_fa")
    end    
  end
  
  def address
    if I18n.locale == :en
      self.read_attribute("address_en")
    else
      self.read_attribute("address_fa")
    end    
  end
end

app/models/category.rb
# encoding: UTF-8
class Category < ActiveRecord::Base
  extend FriendlyId  
  friendly_id :title_fa
  has_many :products
  
  def title    
    if I18n.locale == :en
      self.read_attribute("title_en")
    else
      self.read_attribute("title_fa")
    end    
  end
  
  def description    
    if I18n.locale == :en
      self.read_attribute("description_en")
    else
      self.read_attribute("description_fa")
    end    
  end
end

app/models/license.rb
# encoding: UTF-8
class License < ActiveRecord::Base
  has_attached_file :image, :styles => { :original => "500x500>" , :medium => "300x300>", :small => "220x170>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"],
                                            :message =>  "فرمت عکس صحیح نیست"
                                            
                                            
  def text
    if I18n.locale == :en
      self.read_attribute("text")
    else
      self.read_attribute("text_fa")
    end    
  end
  def title
    if I18n.locale == :en
      self.read_attribute("title_en")
    else
      self.read_attribute("title_fa")
    end    
  end
end

app/models/message.rb
# encoding: UTF-8
class Message < ActiveRecord::Base  
  validates :email, :name, :text, :presence => {:message => 'فیلد های ضروری را پر کنید'}
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => 'ایمیل نامعتبر است.' } 
  
end

app/models/page.rb
# encoding: UTF-8
class Page < ActiveRecord::Base

  def title    
    if I18n.locale == :en
      self.read_attribute("title")
    else
      self.read_attribute("title_fa")
    end    
  end
  
  def description    
    if I18n.locale == :en
      self.read_attribute("description")
    else
      self.read_attribute("description_fa")
    end    
  end
  
end

app/models/photo.rb
# encoding: UTF-8
class Photo < ActiveRecord::Base
  belongs_to :product  
  
  has_attached_file :image, :styles => { :original => "500x500>" , :medium => "300x300>", :small => "320x270>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"],
                                            :message =>  "فرمت عکس صحیح نیست"
  
  def description    
    if I18n.locale == :en
      self.read_attribute("description")
    else
      self.read_attribute("description_fa")
    end    
  end
end

app/models/product.rb
# encoding: UTF-8
class Product < ActiveRecord::Base
  #extend FriendlyId  
  #friendly_id :title_fa
  has_many :photos
  belongs_to :category
  
  def title    
    if I18n.locale == :en
      self.read_attribute("title")
    else
      self.read_attribute("title_fa")
    end    
  end
  
  def description    
    if I18n.locale == :en
      self.read_attribute("description")
    else
      self.read_attribute("description_fa")
    end    
  end
end

app/models/slide.rb
# encoding: UTF-8
class Slide < ActiveRecord::Base
  has_attached_file :image, :styles => {  :medium => "450x450>", :small => "300x350>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def description    
    if I18n.locale == :en
      self.read_attribute("description")
    else
      self.read_attribute("description_fa")
    end    
  end
  def self.get_supersized_js
    
    ret = []
    
    Slide.all.each do |slide|
      ret << "{image : \"#{slide.image(:medium)}\", title : \"<div class='slide-content'> </div>\", thumb : '', url : ''}"
             
    end
    ret.join(",")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :user
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head    
    %title 
      = t("kimiakaran") + ', ' + Category.all.collect(&:title).join(",") #{@head.fetch(:title, '') if @head}
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags 
    %meta{:charset => "utf-8"}
    %meta{:name => "google-site-verification", :content => "p8ANBrP4OE7-rkdHFUnOQtHIsMCJOFI5TBLQiKa8iqM" }
    %meta{:name => "keywords", :content => Category.all.collect(&:title_fa).join(" ")} 
    %meta{:name => "description", :content => "کیمیاکاران, kimiakaran"}
    %meta{content: "no", "http-equiv" => "kimiakaran, کیمیاکاران"}
    = yield(:refresh_meta) if content_for?(:refresh_meta)

  %body{:class => I18n.locale}
    
    / Homepage Slider
    
    :javascript
      window.user_slides = [#{Slide.get_supersized_js}]
      $('ul#supersized li img').css('left', '0');
      $('ul#supersized li img').css('width', '100%');
    #home-slider.en
      -@contact = Page.where(title: "Contact us")
           
      .contact-menu        
        = link_to '#order' ,  :id => "contact-box" do        
          #contact-btn-text{:class => I18n.locale}= 'اطلاعات تماس'
          %i.font-icon-arrow-simple-down#contact-arrow
      .control-nav
        = link_to '#' , :class => "load-item", :id => "prevslide" do    
          %i.font-icon-arrow-simple-left
        = link_to '#' , :class => "load-item", :id => "nextslide" do        
          %i.font-icon-arrow-simple-right
        %ul#slide-list
        = link_to '#work' ,  :id => "nextsection" do        
          %i.font-icon-arrow-simple-down
        #nextsection{:style => "margin-right:1px; text-align:center; "}
          = link_to (image_tag 'flag/fa.png', :title => "کیمیاکاران فردوس", :alt => "کیمیاکاران فردوس"), locale: :fa
          %br
          = link_to (image_tag 'flag/en.png', :title => "KimiaKaran Ferdows", :alt => "KimiaKaran Ferdows"), locale: :en
          
        
    / End Homepage Slider
 
    %header
      .sticky-nav
        %a#mobile-nav.menu-nav{href: "#menu-nav"} Menu
        #logo
          %a#goUp{href: "#home-slider", title: "KIMIAKARAN "}
            =t('kimiakaran')
        - if is_admin?
          .admin_menu.fa
            %h3= 'منوی مدیرسایت'
            = render 'shared/admin_menu'
        #google-search
          = form_tag "http://google.com/search", method: "get",  :target=> "_blank", :class => "contact-form", :id => "contact-form" do   
            %p.contact-name
              .google-field= text_field_tag :q, '', placeholder: t('Google_Search'), :id => "contact_name", :class => I18n.locale    
              .google-submit= submit_tag  t('submit_search'), :name => "sa", :id => "search-submit" , :class => I18n.locale    
              .clear-float
        %nav#menu
          = render 'shared/menu'
    / End Header
    = yield 
    = render "shared/footer"
    / Back To Top
    %a#back-to-top{href: "#"}
      %i.font-icon-arrow-simple-up
    / End Back to Top

    
  = javascript_include_tag "application"
  

app/views/pages/_form.html.haml
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation      
      %ul
        - @page.errors.each do |attr, msg|
          %li= msg

  .field
    = f.label 'عنوان به انگلیسی:'
    = f.text_field :title
  .field
    = f.label 'عنوان به فارسی:'
    = f.text_field :title_fa
  .field.editor
    = f.label 'متن به فارسی:'
    = f.cktext_area :text, :class => "form-control ckeditor"
  .field.editor
    = f.label 'متن به انگلیسی:'
    = f.cktext_area :text_fa, :class => "form-control ckeditor"
  .actions
    = f.submit 'ثبت', :class => "btn btn-default"

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', @page
\|
= link_to 'Back', pages_path

app/views/pages/index.html.haml
.page.fa.other-page  
  %h1 لیست صفحات متنی
  - if is_admin?
    = link_to 'ایجاد صفحه متنی جدید', new_page_path, :class => "btn btn-default"

  %table
    %tr
      %th عنوان صفحه
      %th عملیات

    - @pages.each do |page|
      %tr
        %td= page.title        
        %td
          = link_to 'مشاهده', page
          \|          
          = link_to 'ویرایش', edit_page_path(page)
          \|
          = link_to 'حذف', page, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }

  

  

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
%p#notice= notice

%h1
  = @page.title
%p  
  =raw @page.text

= link_to 'ویرایش', edit_page_path(@page)
\|
= link_to 'بازگشت', :back

app/views/shared/_admin_menu.html.haml
%ul  
  %li
    = link_to "مدیریت گروه محصولات", Category
  %li
    = link_to "مدیریت محصولات", products_path
  %li
    = link_to "افزودن تصویر به محصول", photos_path
  %li
    = link_to "مدیریت اسلایدر", Slide  
  %li
    = link_to "مجوزها و پروانه ها", License  
  %li
    = link_to "افزودن نمایندگی", Agent
  %li
    = link_to "مدیریت صفحات متنی", Page
  %li
    = link_to "پروفایل مدیرسایت", User
  %li
    =link_to 'خروج', delete_session_path

app/views/shared/_footer.html.haml
/ Footer
%footer.en
  %p.credits
    \©COPYRIGHT KIMIA KARAN.
    = link_to 'DEVELOPED', url_with_protocol('raush.net')    
    by
    = link_to 'RAUSH', url_with_protocol('raush.net')    
/ End Footer

app/views/shared/_menu.html.haml
%ul#menu-nav  
  %li.current
    = link_to t('home'), '#home-slider'      
  %li
    = link_to t('work'), '#work'      
  %li
    = link_to t('about'), '#about'      
  %li 
    = link_to t('contact'), '#contact'
  %li 
    = link_to t('order_menu'), '#order'

    
    

app/views/shared/_msg_form.html.haml
= form_for @message ||= Message.new, :html => {:class => "contact-form", :id => "contact-form"} do |f|
  - if @message.errors.any?
    
    #error_explanation
      %ul
        - @message.errors.each do |attr, msg|
          %li= msg 
      
  -if flash[:SendMsg]        
    .alert.alert-success= flash[:SendMsg]
  -if flash[:MsgError]        
    .alert.alert-danger= flash[:MsgError]
 
  %p.contact-name
    = f.text_field :name,  placeholder: t('msg.name'), :id => "contact_name", :class => I18n.locale    
    
  %p.contact-email
    = f.text_field :email, placeholder: t('msg.email') , :id => "contact_email", :class => I18n.locale
    
  %p.contact-phone    
    = f.text_field :phone_number, placeholder:  t('msg.phone')  , :id => "contact_phone", :class => I18n.locale
    
  %p.contact-message    
    = f.text_area :text, cols: "40", placeholder:  t('msg.text'), rows: "15", :style => "resize:none", :id => "contact_message", :class => I18n.locale
    
         
  %p.contact-submit{:class => I18n.locale}
    = f.submit  t('msg.send'), :class=> "submit", :id => "contact-submit"
    

app/views/shared/_order_form.html.haml
= form_for @message ||= Message.new, :html => {:class => "contact-form", :id => "contact-form"} do |f|
  - if @message.errors.any?
    .alert.alert-danger
      %ul
        - @message.errors.each do |attr, msg|
          %li= msg 
      
  -if flash[:SendOrder]        
    .alert.alert-success= flash[:SendOrder]
  -if flash[:MsgError]        
    .alert.alert-danger= flash[:MsgError]
  = f.hidden_field :message_type, :value => 1
  %p.contact-name    
    
    = f.text_field :name, placeholder: t('msg.name'), :id => "order_name", :class => I18n.locale    
    
  %p.contact-email    
    
    = f.email_field :email, placeholder: t('msg.email') , :id => "order_email", :class => I18n.locale
    
  %p.contact-phone    
    = f.text_field :phone_number,placeholder:  t('msg.phone')  , :id => "order_phone", :class => I18n.locale
    
  %p.contact-message
    
    = f.text_area :text, cols: "40", placeholder:  t('order.text'), rows: "15", :style => "resize:none", :id => "order_message", :class => I18n.locale
    
         
  %p.contact-submit{:class => I18n.locale}
    = f.submit  t('order.send'), :class=> "submit", :id => "order-submit"
    
  
:javascript   
  $(':submit').click(function(e) {
    $(':text.needed, textarea.needed').each(function() {
      if ($(this).val().length == 0) {
        $(this).css('border', '2px solid red');
        e.preventDefault();
      }
    });
  });