config/routes.rb
PackB::Application.routes.draw do
  resources :agents

  resources :photos

  scope "(:locale)", :locale => /en|fa/ do  
    resources :pictures
    resources :user_messages

    resources :messages

    resources :categories
    
    resources :products
    resources :licenses

    resources :slides

    resources :users

    resources :pages
  end
  mount Ckeditor::Engine => '/ckeditor'
  
  root :to => 'static#home'
  get "login" => "users#login"  
  get "googlebc5f5c16062b24b0" => "static#googlebc5f5c16062b24b0"  
  get "sitemap.xml" => "static#sitemap", :format => "xml", :as => :sitemap
  post "create_session" => "users#create_session", :as => :create_session
  get "delete_session" => "users#delete_session", :as => :delete_session

end

app/models/photo.rb
# encoding: UTF-8
class Photo < ActiveRecord::Base
  belongs_to :product  
  
  has_attached_file :image, :styles => { :original => "500x500>" , :medium => "300x300>", :small => "320x270>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"],
                                            :message =>  "فرمت عکس صحیح نیست"
  
  def description    
    if I18n.locale == :en
      self.read_attribute("description")
    else
      self.read_attribute("description_fa")
    end    
  end
end

app/controllers/photos_controller.rb
# encoding: UTF-8
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_filter :check_autentication
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:description_fa, :description_en, :product_id, :image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
= form_for @photo do |f|
  - if @photo.errors.any?
    #error_explanation      
      %ul
        - @photo.errors.each do |attr, msg|
          %li= msg

  .field
    = f.label 'محصول مربوط:'
    - if @photo.product_id.present?
      %b= @photo.product.title
    - else
      = f.select(:product_id, Product.all.collect {|u| [u.title_fa, u.id]}, :prompt => ' بخش را انتخاب کنید.') 
    
  .field
    = f.label 'تصویر:'
    - if @photo.image.present?
      = image_tag @photo.image(:small)
    = f.file_field :image
  .field.editor
    = f.label 'توضیحات به فارسی:'
    = f.text_area :description_fa , :class => "ckeditor" 
  .field.editor
    = f.label 'توضیحات به انگلیسی:'
    = f.text_area:description_en, :class => "ckeditor"
  
  .actions
    = f.submit 'ثبت', :class => "btn btn-default"

app/views/photos/edit.html.haml
.fa.other-page  
  %h1 ویرایش تصویر محصول

  = render 'form'

  = link_to 'مشاهده', @photo
  \|
  = link_to 'بازگشت', photos_path

app/views/photos/index.html.haml
.fa.other-page
  %h1 لیست تصاویر محصولات
  - if is_admin?
    = link_to 'تصویر جدید', new_photo_path, :class => "btn btn-default"
  %table
    %tr            
      %th ردیف
      %th توضیحات
      %th محصول مربوطه
      %th نام تصویر      
      %th تصویر     
      %th عملیات
      

    - @photos.each_with_index do |photo, i|
      %tr      
        %td= (i+1)
        %td= photo.description        
        %td
          - if photo.product.present?
            = photo.product.title
        %td= photo.image_file_name
        %td= photo.image(:small)
        %td
          - if is_admin?
            = link_to 'مشاهده', photo
            \|
            = link_to 'ویرایش', edit_photo_path(photo)
            \|
            = link_to 'حذف', photo, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }



  

app/views/photos/new.html.haml
.fa.other-page
  %h1 تصویر جدید

  = render 'form'

  = link_to 'بازگشت', :back

app/views/photos/show.html.haml
.fa.other-page
      
  %p#notice= notice

  %p
    = image_tag @photo.image(:small)
  %p
    %b توضیحات
    = @photo.description
  
  %p
    %b گروه مربوط
    = @photo.product.title

  = link_to 'ویرایش', edit_photo_path(@photo)
  \|
  = link_to 'بازگشت', :back