config/routes.rb
PackB::Application.routes.draw do
  resources :agents

  resources :photos

  scope "(:locale)", :locale => /en|fa/ do  
    resources :pictures
    resources :user_messages

    resources :messages

    resources :categories
    
    resources :products
    resources :licenses

    resources :slides

    resources :users

    resources :pages
  end
  mount Ckeditor::Engine => '/ckeditor'
  
  root :to => 'static#home'
  get "login" => "users#login"  
  get "googlebc5f5c16062b24b0" => "static#googlebc5f5c16062b24b0"  
  get "sitemap.xml" => "static#sitemap", :format => "xml", :as => :sitemap
  post "create_session" => "users#create_session", :as => :create_session
  get "delete_session" => "users#delete_session", :as => :delete_session

end

app/models/category.rb
# encoding: UTF-8
class Category < ActiveRecord::Base
  extend FriendlyId  
  friendly_id :title_fa
  has_many :products
  
  def title    
    if I18n.locale == :en
      self.read_attribute("title_en")
    else
      self.read_attribute("title_fa")
    end    
  end
  
  def description    
    if I18n.locale == :en
      self.read_attribute("description_en")
    else
      self.read_attribute("description_fa")
    end    
  end
end

app/controllers/categories_controller.rb
# encoding: UTF-8
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title_en, :title_fa, :description_en, :description_fa)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation      
      %ul
        - @category.errors.each do |attr, msg|
          %li= msg

  .field
    = f.label 'عنوان به انگلیسی:'
    = f.text_field :title_en
  .field
    = f.label 'عنوان به فارسی:'
    = f.text_field :title_fa
  .field
    = f.label 'توضیحات به انگلیسی:'
    = f.text_area :description_en
  .field
    = f.label 'توضیحات به فارسی:'
    = f.text_area :description_fa
  .actions
    = f.submit 'ثبت', :class => "btn btn-default"

app/views/categories/edit.html.haml
.fa.other-page  
  %h1 ویرایش گروه محصولات

  = render 'form'

  = link_to 'مشاهده', @category
  \|
  = link_to 'بازگشت', :back

app/views/categories/index.html.haml
.page.fa.other-page{:style => "height:100%"}
  - if is_admin?
    = link_to 'ایجاد دسته جدید محصولات', new_category_path, :class => "btn btn-default"
  / Our Work Section
  #work
    - @categories.each do |category|
      %div
        %p= category.title
        
        = link_to 'مشاهده بیشتر', category
        \|
        = link_to 'ویرایش', edit_product_path(category)
        \|
        = link_to 'حذف', category, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }
             
.clear-float              
   
    

app/views/categories/new.html.haml
.fa.other-page
  %h1 گروه جدید برای محصولات

  = render 'form'

  = link_to 'بازگشت', :back

app/views/categories/show.html.haml
.fa.other-page    

  %p
    %b عنوان گروه
    = @category.title
  
  %p
    
    =raw @category.description
  

  = link_to 'ویرایش', edit_category_path(@category)
  \|
  = link_to 'بازگشت', :back